### ISSUE TITLE
[RFE] More Useful Logging Return for VSC

### ISSUE THREAD

**Issue by sadsfae** [quadsproject/quads#455]
For the VSC tool if there are no clouds in a defined cloud it will give an error (which it should) but I think it should be more informative.

```
[root@quads ~]# /opt/quads/quads/tools/verify_switchconf.py --cloud cloud21
Traceback (most recent call last):
  File "/opt/quads/quads/tools/verify_switchconf.py", line 157, in <module>
    verify(args.cloud, args.host, args.change)
  File "/opt/quads/quads/tools/verify_switchconf.py", line 34, in verify
    if _cloud_obj != first_host.cloud:
AttributeError: 'NoneType' object has no attribute 'cloud'
```

Instead we might say something like `This environment currently has no active hosts" or similar.

**Comment by sadsfae** [comment]
Implemented: verifying an empty cloud now logs 'No hosts found on cloud.' instead of an AttributeError traceback (src/quads/plugins/builtin/switches/juniper.py:217).
